const path = require('path');

const repoRoot = path.resolve(__dirname, '..');

module.exports = {
  apps: [
    {
      name: 'legacy-api-dev',
      script: 'server-production.js',
      cwd: repoRoot,
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'development',
        RHAUTT_RUNTIME_PROFILE: 'safe',
      },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'legacy-api-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'legacy-api-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'nestjs-api-dev',
      script: 'scripts/start-api.js',
      cwd: repoRoot,
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'development',
        API_START_MODE: 'typescript',
      },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'nestjs-api-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'nestjs-api-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'dealer-workbench-dev',
      script: path.join(repoRoot, 'scripts', 'dealer-workbench', 'dev-logged.js'),
      cwd: repoRoot,
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'development',
        API_URL: 'http://localhost:5500',
      },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'dealer-workbench-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'dealer-workbench-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'consumer-diagnosis-dev',
      script: path.join(repoRoot, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: 'dev --port 4001',
      cwd: path.join(repoRoot, 'apps', 'consumer-diagnosis'),
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: { NODE_ENV: 'development' },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'consumer-diagnosis-pm2.out.log'),
      error_file: path.join(
        repoRoot,
        'runtime-logs',
        'startup',
        'consumer-diagnosis-pm2.error.log'
      ),
      merge_logs: true,
    },
    {
      name: 'customer-portal-dev',
      script: path.join(repoRoot, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: 'dev --port 4002',
      cwd: path.join(repoRoot, 'apps', 'customer-portal'),
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: { NODE_ENV: 'development' },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'customer-portal-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'customer-portal-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'public-portal-dev',
      script: path.join(repoRoot, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: 'dev --port 4005',
      cwd: path.join(repoRoot, 'apps', 'public-portal'),
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: { NODE_ENV: 'development' },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'public-portal-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'public-portal-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'nexus-console-dev',
      script: path.join(repoRoot, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: 'dev --port 4010',
      cwd: path.join(repoRoot, 'apps', 'nexus-console'),
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: { NODE_ENV: 'development' },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'nexus-console-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'nexus-console-pm2.error.log'),
      merge_logs: true,
    },
    {
      name: 'brand-console-dev',
      script: path.join(repoRoot, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: 'dev --port 4012',
      cwd: path.join(repoRoot, 'apps', 'brand-console'),
      interpreter: process.execPath,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      kill_timeout: 5000,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'development',
        NEXUS_API_URL: 'http://localhost:3300',
        NEXUS_API_PREFIX: '/api/v2',
        JWT_SECRET: 'local-dev-jwt-secret-change-me',
        EVERHOT_TENANT_ID: 'e5e40000-0000-4000-8000-000000000001',
      },
      out_file: path.join(repoRoot, 'runtime-logs', 'startup', 'brand-console-pm2.out.log'),
      error_file: path.join(repoRoot, 'runtime-logs', 'startup', 'brand-console-pm2.error.log'),
      merge_logs: true,
    },
  ],
};
