/**
 * @class AgentCoordinator
 * @description Auto-generated by Hermes Evolution
 * @version 2.0.0
 * @author Hermes AI
 * @since 2026-04-18
 */
/**
 * Agent协调器 - 管理多Agent并行工作
 *
 * 功能：
 * 1. 协调多个Agent并行执行任务
 * 2. 任务队列管理
 * 3. 资源分配和冲突解决
 * 4. 实时进度监控
 * 5. 自检和开发任务并行执行
 */

class AgentCoordinator {
  constructor() {
    this.agents = new Map();
    this.taskQueue = [];
    this.runningTasks = new Map();
    this.completedTasks = [];
    this.maxConcurrentTasks = 5;

    // Agent类型定义
    this.agentTypes = {
      SELF_CHECK: {
        name: '自检Agent',
        priority: 'background',
        interval: 3600000, // 1小时
      },
      DEVELOPMENT: {
        name: '开发Agent',
        priority: 'foreground',
      },
      TESTING: {
        name: '测试Agent',
        priority: 'background',
      },
      MONITORING: {
        name: '监控Agent',
        priority: 'background',
        interval: 30000, // 30秒
      },
    };
  }

  /**
   * 注册Agent
   */
  registerAgent(agentId, agentConfig) {
    this.agents.set(agentId, {
      id: agentId,
      ...agentConfig,
      status: 'idle',
      currentTask: null,
      lastActivity: null,
    });

    console.log(`✅ Agent注册成功: ${agentConfig.name} (${agentId})`);
  }

  /**
   * 启动Agent
   */
  startAgent(agentId) {
    const agent = this.agents.get(agentId);
    if (!agent) {
      console.error(`Agent不存在: ${agentId}`);
      return false;
    }

    agent.status = 'active';
    agent.lastActivity = new Date();

    // 如果是定时任务，启动定时器
    if (agent.interval) {
      agent.timer = setInterval(() => {
        this.executeAgentTask(agentId);
      }, agent.interval);
    }

    console.log(`🚀 Agent启动: ${agent.name}`);
    return true;
  }

  /**
   * 停止Agent
   */
  stopAgent(agentId) {
    const agent = this.agents.get(agentId);
    if (!agent) {
      return false;
    }

    agent.status = 'idle';

    // 清除定时器
    if (agent.timer) {
      clearInterval(agent.timer);
      agent.timer = null;
    }

    // 停止当前任务
    if (agent.currentTask) {
      this.cancelTask(agent.currentTask.id);
    }

    console.log(`⏹️ Agent停止: ${agent.name}`);
    return true;
  }

  /**
   * 添加任务到队列
   */
  addTask(task) {
    const taskWithId = {
      id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      status: 'pending',
      createdAt: new Date(),
      ...task,
    };

    this.taskQueue.push(taskWithId);

    // 尝试立即执行
    this.processTaskQueue();

    return taskWithId.id;
  }

  /**
   * 处理任务队列
   */
  processTaskQueue() {
    // 检查是否可以执行更多任务
    if (this.runningTasks.size >= this.maxConcurrentTasks) {
      return;
    }

    // 按优先级排序任务
    const sortedTasks = this.taskQueue.sort((a, b) => {
      const priorityOrder = { critical: 0, high: 1, normal: 2, low: 3 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });

    // 执行任务
    while (this.runningTasks.size < this.maxConcurrentTasks && sortedTasks.length > 0) {
      const task = sortedTasks.shift();
      this.executeTask(task);
    }
  }

  /**
   * 执行任务
   */
  async executeTask(task) {
    // 查找可用的Agent
    const agent = this.findAvailableAgent(task.agentType);
    if (!agent) {
      // 没有可用Agent，放回队列
      this.taskQueue.push(task);
      return;
    }

    // 更新任务和Agent状态
    task.status = 'running';
    task.startedAt = new Date();
    this.runningTasks.set(task.id, task);

    agent.status = 'busy';
    agent.currentTask = task;
    agent.lastActivity = new Date();

    console.log(`🔄 执行任务: ${task.name} (Agent: ${agent.name})`);

    try {
      // 执行任务
      const result = await task.execute(task.params);

      // 任务完成
      task.status = 'completed';
      task.completedAt = new Date();
      task.result = result;

      this.completedTasks.push(task);
      this.runningTasks.delete(task.id);

      // 释放Agent
      agent.status = 'idle';
      agent.currentTask = null;

      console.log(`✅ 任务完成: ${task.name}`);

      // 处理队列中的下一个任务
      this.processTaskQueue();
    } catch (error) {
      // 任务失败
      task.status = 'failed';
      task.completedAt = new Date();
      task.error = error.message;

      this.runningTasks.delete(task.id);

      // 释放Agent
      agent.status = 'idle';
      agent.currentTask = null;

      console.error(`❌ 任务失败: ${task.name}`, error);

      // 处理队列中的下一个任务
      this.processTaskQueue();
    }
  }

  /**
   * 执行Agent定时任务
   */
  async executeAgentTask(agentId) {
    const agent = this.agents.get(agentId);
    if (!agent || agent.status !== 'active') {
      return;
    }

    // 检查Agent是否正在执行任务
    if (agent.status === 'busy') {
      return;
    }

    // 执行Agent的定时任务
    if (agent.onInterval) {
      try {
        await agent.onInterval();
        agent.lastActivity = new Date();
      } catch (error) {
        console.error(`Agent定时任务执行失败: ${agent.name}`, error);
      }
    }
  }

  /**
   * 查找可用的Agent
   */
  findAvailableAgent(agentType) {
    for (const [agentId, agent] of this.agents) {
      if (agent.type === agentType && agent.status === 'idle') {
        return agent;
      }
    }
    return null;
  }

  /**
   * 取消任务
   */
  cancelTask(taskId) {
    const task = this.runningTasks.get(taskId);
    if (!task) {
      // 检查队列中的任务
      const queueIndex = this.taskQueue.findIndex((t) => t.id === taskId);
      if (queueIndex !== -1) {
        this.taskQueue.splice(queueIndex, 1);
        return true;
      }
      return false;
    }

    // 取消正在运行的任务
    task.status = 'cancelled';
    task.completedAt = new Date();
    this.runningTasks.delete(taskId);

    // 释放Agent
    const agent = this.agents.get(task.agentId);
    if (agent && agent.currentTask && agent.currentTask.id === taskId) {
      agent.status = 'idle';
      agent.currentTask = null;
    }

    console.log(`🚫 任务取消: ${task.name}`);
    return true;
  }

  /**
   * 获取系统状态
   */
  getSystemStatus() {
    return {
      agents: Array.from(this.agents.values()).map((agent) => ({
        id: agent.id,
        name: agent.name,
        status: agent.status,
        currentTask: agent.currentTask ? agent.currentTask.name : null,
        lastActivity: agent.lastActivity,
      })),
      queue: {
        pending: this.taskQueue.length,
        running: this.runningTasks.size,
        completed: this.completedTasks.length,
      },
      maxConcurrentTasks: this.maxConcurrentTasks,
    };
  }

  /**
   * 获取任务状态
   */
  getTaskStatus(taskId) {
    // 检查运行中的任务
    const runningTask = this.runningTasks.get(taskId);
    if (runningTask) {
      return runningTask;
    }

    // 检查队列中的任务
    const queuedTask = this.taskQueue.find((t) => t.id === taskId);
    if (queuedTask) {
      return queuedTask;
    }

    // 检查已完成的任务
    const completedTask = this.completedTasks.find((t) => t.id === taskId);
    if (completedTask) {
      return completedTask;
    }

    return null;
  }

  /**
   * 设置最大并发任务数
   */
  setMaxConcurrentTasks(max) {
    this.maxConcurrentTasks = max;
    console.log(`📊 最大并发任务数设置为: ${max}`);

    // 尝试处理队列
    this.processTaskQueue();
  }

  /**
   * 清理已完成的任务
   */
  cleanupCompletedTasks(olderThanHours = 24) {
    const cutoffTime = new Date(Date.now() - olderThanHours * 60 * 60 * 1000);
    this.completedTasks = this.completedTasks.filter((task) => task.completedAt > cutoffTime);

    console.log(`🧹 清理了${this.completedTasks.length}个已完成任务`);
  }
}

// 导出单例实例
const agentCoordinator = new AgentCoordinator();

module.exports = agentCoordinator;
