/* eslint-disable */
// Generated by scripts/contracts/generate-openapi-client.js
// Do not edit manually. Update contracts/openapi/rhautt-nexus-v2.openapi.json and rerun npm run contracts:generate.
export const OPENAPI_SHA256 = '4f09d25ed6f83403036b75f2feea4d47c98cb3dd89f18266d445b9c33feb9949';
export const OPENAPI_TITLE = "Rhautt Nexus / 瑞合数智枢纽 API";

export type AnalyticsOverview = {
  scope: {
  tenantId: string;
  dealerId?: string | null;
  storeId?: string | null;
  role?: string | null;
  visibility: "tenant-wide" | "dealer-scoped";
};
  totals: {
  dealers: number;
  stores: number;
  staff: number;
  customers: number;
  pipeline: number;
  wonAmount: number;
  quotedAmount: number;
};
  stages: Record<string, {
  count: number;
  amount: number;
}>;
  dealerPerformance: Array<{
  _id?: string | null;
  dealerId?: string | null;
  opportunityCount: number;
  estimatedPipeline: number;
  wonCount: number;
  quotedCount: number;
}>;
  generatedAt: string;
  storageMode?: string;
};

export type AnalyticsOverviewEnvelope = {
  success: true;
  data: AnalyticsOverview;
};

export type AuditEvent = {
  id?: string;
  _id?: string;
  tenantId: string;
  actorUserId?: string | null;
  action: string;
  resourceType: string;
  resourceId?: string | null;
  before?: Record<string, unknown> | null;
  after?: Record<string, unknown> | null;
  ip?: string | null;
  userAgent?: string | null;
  createdAt?: string;
  storageMode?: string;
};

export type AuditEventPage = {
  items: Array<AuditEvent>;
  pagination: Pagination;
  storageMode?: string;
};

export type AuditEventsEnvelope = {
  success: true;
  data: AuditEventPage;
};

export type CapabilityRegistryItem = {
  assetId?: string;
  category?: SystemCategory;
  iotDeviceId?: string | null;
  capabilities?: Array<string>;
  bindingStatus?: "not_started" | "prepared" | "partial" | "bound" | "failed";
  controlBoundary: "lifecycle_handoff_only";
};

export type ContractApproval = {
  required: boolean;
  status: "not_required" | "pending" | "approved" | "rejected";
  reason?: string | null;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
};

export type ContractApprovalInput = {
  decision: "approved" | "rejected";
  reason?: string;
  decidedAt?: string;
};

export type ContractDeliveryStartEnvelope = {
  success: true;
  data: {
  contract: ContractV2;
  lifecycleLink: LifecycleHandover;
};
};

export type ContractDeliveryStartInput = {
  projectAddress?: string;
  systems?: Array<string>;
  devices?: Array<Record<string, unknown>>;
  installedAssets?: Array<Record<string, unknown>>;
  iot?: Record<string, unknown>;
  servicePlan?: Record<string, unknown>;
};

export type ContractEnvelope = {
  success: true;
  data: ContractV2;
};

export type ContractFromQuotationInput = {
  quotationId: string;
  quotationNo?: string;
  customerId?: string;
  opportunityId?: string;
  paymentSchedule?: Array<ContractPaymentScheduleItem>;
  approval?: Record<string, unknown>;
  lifecycleHandoff?: Record<string, unknown>;
  terms?: Record<string, unknown>;
};

export type ContractLifecycleHandoff = {
  required: boolean;
  status: "not_started" | "ready" | "linked" | "registered";
  iotBridgeKey?: string;
  servicePlanCode?: string;
  handoffBoundary: "lifecycle_handoff_only";
};

export type ContractListEnvelope = {
  success: true;
  data: {
  items: Array<ContractV2>;
  pagination: Pagination;
};
};

export type ContractMutationEnvelope = {
  success: true;
  data: {
  contract: ContractV2;
  quote?: Record<string, unknown>;
  created: boolean;
};
};

export type ContractPaymentInput = {
  key?: string;
  index?: number;
  amount: number;
  method?: string;
  receiptNo?: string;
  note?: string;
  paidAt?: string;
};

export type ContractPaymentScheduleItem = {
  key: string;
  label: string;
  ratio?: number;
  amount: number;
  dueStage?: string;
  dueDate?: string | null;
  status: "pending" | "invoiced" | "paid" | "overdue" | "waived";
  paidAmount?: number;
  paidAt?: string | null;
  method?: string;
  receiptNo?: string;
  note?: string;
};

export type ContractPricingSnapshot = {
  quotationNo?: string;
  quoteId?: string;
  revision?: number;
  source?: string;
  currency?: "CNY";
  customerTotal: number;
  directCost: number;
  dealerMargin: number;
  monthlyPayment: number;
  marginGuard: Record<string, unknown>;
};

export type ContractSignature = {
  method: "offline" | "electronic" | "customer_portal_confirmation" | "none";
  status: "not_started" | "pending" | "signed" | "rejected";
  customerSigner?: string;
  companySigner?: string;
  signedAt?: string;
  evidenceUrl?: string;
  termsVersion?: string;
  customerIp?: string;
};

export type ContractSignatureInput = {
  method?: "offline" | "electronic" | "customer_portal_confirmation";
  customerSigner?: string;
  companySigner?: string;
  evidenceUrl?: string;
  contractPdfUrl?: string;
  customerIp?: string;
  signedAt?: string;
};

export type ContractV2 = {
  id?: string;
  _id?: string;
  tenantId: string;
  dealerId?: string | null;
  storeId?: string | null;
  customerId: string;
  opportunityId?: string | null;
  quotationId?: string;
  lifecycleLinkId?: string;
  contractNo: string;
  source?: "quotation-v2" | "manual" | "migration";
  status: "draft" | "pending_approval" | "pending_signature" | "signed" | "delivery_started" | "cancelled" | "voided";
  paymentStatus: "not_started" | "partial" | "paid" | "overdue" | "waived";
  project?: Record<string, unknown>;
  systemFamilies?: Array<string>;
  pricingSnapshot: ContractPricingSnapshot;
  paymentSchedule: Array<ContractPaymentScheduleItem>;
  approval: ContractApproval;
  signature: ContractSignature;
  lifecycleHandoff: ContractLifecycleHandoff;
  deliverables?: Record<string, unknown>;
  terms?: Record<string, unknown>;
  signedAt?: string;
  deliveryStartedAt?: string;
};

export type CreateDealerInput = {
  code: string;
  name: string;
  province?: string | null;
  city?: string | null;
  contact?: Record<string, string>;
  contractLevel?: string;
  status?: string;
};

export type CreateStoreInput = {
  dealerId: string;
  code: string;
  name: string;
  city?: string | null;
  address?: string | null;
  managerUserId?: string | null;
  status?: string;
};

export type CreateTenantInput = {
  code: string;
  name: string;
  type?: "hq" | "regional" | "dealer_group";
  status?: "active" | "inactive" | "suspended";
  settings?: Record<string, unknown>;
};

export type Dealer = {
  id: string;
  tenantId: string;
  code: string;
  name: string;
  province?: string | null;
  city?: string | null;
  contact: Record<string, string>;
  contractLevel: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

export type DiagnosisCompletion = {
  moduleId: "rysnova-consumer-system";
  moduleDeploymentMode: "rhautt-portal-embedded" | "standalone";
  source: "rysnova-ai-diagnosis";
  customer: Record<string, unknown>;
  opportunity: Record<string, unknown>;
  duplicate?: boolean;
  diagnosis: DiagnosisSnapshot;
  solutions: Array<DiagnosisSolutionTier>;
  recommendedTierId: "essential" | "balanced" | "premium";
  visualPackages: DiagnosisVisualPackages;
  quotationSummary: DiagnosisQuotationSummary;
  customerReport: DiagnosisCustomerReport;
  nextActions: Array<string>;
  iotBoundary: "lifecycle_handoff_only";
  moduleNamespace: "rysnova";
  dataNamespace: "rysnova";
};

export type DiagnosisCompletionEnvelope = {
  success: true;
  data: DiagnosisCompletion;
};

export type DiagnosisCustomerReport = {
  id: string;
  type: "rysnova-ai-diagnosis-report";
  customerId: string;
  opportunityId: string;
  shareUrl: string;
  shareToken?: string;
  generatedAt: string;
  visibleSections: Array<string>;
};

export type DiagnosisPublicReport = {
  reportId: string;
  moduleId: "rysnova-consumer-system";
  moduleDeploymentMode: "rhautt-portal-embedded" | "standalone";
  source: "rysnova-ai-diagnosis";
  status: "active";
  channel?: string;
  customer: Record<string, unknown>;
  opportunity?: Record<string, unknown>;
  project: {
  city?: string;
  address?: string;
  area: number;
  houseType?: string;
  familyMembers?: number | string | null;
} & Record<string, unknown>;
  diagnosis: DiagnosisSnapshot;
  solutions: Array<DiagnosisSolutionTier>;
  recommendedTierId: "essential" | "balanced" | "premium";
  visualPackages: DiagnosisVisualPackages;
  quotationSummary: DiagnosisQuotationSummary;
  customerReport: DiagnosisCustomerReport;
  nextActions: Array<string>;
  iotBoundary: "lifecycle_handoff_only";
  generatedAt?: string;
  updatedAt?: string;
  moduleNamespace: "rysnova";
  dataNamespace: "rysnova";
};

export type DiagnosisPublicReportEnvelope = {
  success: true;
  data: DiagnosisPublicReport;
};

export type DiagnosisQuotationSummary = {
  status: "draft-ready";
  recommendedTierId: string;
  estimatedTotal: number;
  monthlyPayment: number;
  currency: "CNY";
};

export type DiagnosisSnapshot = {
  painPoints: Array<string>;
  systems: Array<"hot_water" | "heating" | "water_treatment" | "fresh_air" | "air" | "smart_control">;
  completedAt: string;
};

export type DiagnosisSolutionTier = {
  id: "essential" | "balanced" | "premium";
  name: string;
  systems: Array<string>;
  systemLabels: Array<string>;
  estimatedTotal: number;
  monthlyPayment: number;
  roi: {
  energySavingRate: number;
  comfortConfidence: number;
};
  equipmentBrands: Array<"Rheem" | "Ruud" | "Everhot">;
};

export type DiagnosisVisualArtifact = {
  type: "principle-diagram" | "layout-2d" | "scene3d";
  label: "设计原理图" | "2D布局图" | "3D示意图";
  status: string;
  url?: string | null;
  inlineSvg?: string | null;
  drawingSetId?: string | null;
  scene?: Record<string, unknown>;
  previewSvg?: string | null;
  thumbnail?: string | null;
  quality?: string;
};

export type DiagnosisVisualPackages = {
  version: string;
  generatedAt: string;
  status: "ready" | "partial";
  tiers: {
  essential: DiagnosisVisualTierPackage;
  balanced: DiagnosisVisualTierPackage;
  premium: DiagnosisVisualTierPackage;
};
};

export type DiagnosisVisualSet = {
  principleDiagram: DiagnosisVisualArtifact;
  layout2d: DiagnosisVisualArtifact;
  scene3d: DiagnosisVisualArtifact;
};

export type DiagnosisVisualTierPackage = {
  tier: "essential" | "balanced" | "premium";
  tierName: string;
  generatedAt: string;
  status: "ready" | "partial";
  visuals: DiagnosisVisualSet;
  drawingSet?: Record<string, unknown> | null;
};

export type ErrorEnvelope = {
  success: false;
  error: string;
};

export type HandoverStatus = "pending" | "ready" | "sent" | "accepted" | "failed";

export type HealthObservability = {
  service: string;
  boundary: "observability-baseline";
  environment: string;
  version: string;
  signals: ObservabilitySignals;
  slo: ObservabilitySlo;
  metrics: ObservabilityMetrics;
  timestamp: string;
};

export type HealthObservabilityEnvelope = {
  success: true;
  data: HealthObservability;
};

export type InstalledAsset = InstalledAssetInput;

export type InstalledAssetInput = {
  assetId?: string;
  sourceDeviceId?: string;
  productId?: string;
  brand?: string;
  category?: SystemCategory;
  name?: string;
  model?: string;
  serialNumber?: string;
  installLocation?: string;
  iotDeviceId?: string | null;
  capabilities?: Array<string>;
  status?: InstalledAssetStatus;
  warranty?: Warranty;
  servicePlanCode?: string;
};

export type InstalledAssetStatus = "planned" | "installed" | "bound" | "online" | "offline" | "service_required";

export type IotHandoff = {
  platform: string;
  homeId?: string;
  accountId?: string;
  bindingStatus: "not_started" | "prepared" | "partial" | "bound" | "failed";
  handoffBoundary: "lifecycle_handoff_only";
  capabilityRegistry: Array<CapabilityRegistryItem>;
  boundAt?: string;
};

export type IotHandoffInput = {
  platform?: string;
  homeId?: string;
  accountId?: string;
  bindingStatus?: "not_started" | "prepared" | "partial" | "bound" | "failed";
  handoffBoundary?: "lifecycle_handoff_only";
  capabilityRegistry?: Array<CapabilityRegistryItem>;
};

export type LifecycleAcceptanceInput = {
  acceptedAt?: string;
  iot?: IotHandoffInput;
  servicePlan?: ServicePlanInput;
};

export type LifecycleCustomerAcceptance = {
  status: "not-started" | "pending" | "accepted";
  acceptedAt?: string | null;
};

export type LifecycleCustomerConstruction = {
  state: "not-started" | "active" | "completed";
  currentMilestone: string;
  progressPercent: number;
};

export type LifecycleCustomerIot = {
  platform?: string;
  homeId?: string | null;
  bindingStatus: "not_started" | "prepared" | "partial" | "bound" | "failed";
  handoverStatus: HandoverStatus;
  handoffBoundary: "lifecycle_handoff_only";
  capabilityRegistry: Array<CapabilityRegistryItem>;
};

export type LifecycleCustomerMilestone = {
  state: LifecycleProjectState;
  label: string;
  description: string;
  status: "pending" | "active" | "done";
  customerVisibleState?: string;
  progressPercent: number;
};

export type LifecycleCustomerNextAction = {
  title: string;
  description: string;
  actionType: string;
  href?: string;
  visibility: "customer-visible";
};

export type LifecycleCustomerProject = {
  tenantId: string;
  customerId: string;
  contractId: string;
  opportunityId?: string;
  projectAddress?: string;
  projectState: LifecycleProjectState;
  customerVisibleState: string;
  progressPercent: number;
  currentMilestone?: string;
  lifecycleStage?: LifecycleStage;
  handoverStatus?: HandoverStatus;
  references: LifecycleCustomerReferences;
  solution: LifecycleCustomerSolution;
  quotation: LifecycleCustomerQuotation;
  construction: LifecycleCustomerConstruction;
  acceptance: LifecycleCustomerAcceptance;
  servicePlan: ServicePlan;
  installedAssets: Array<InstalledAsset>;
  iot: LifecycleCustomerIot;
  milestones: Array<LifecycleCustomerMilestone>;
  nextAction: LifecycleCustomerNextAction;
  visibility: LifecycleCustomerVisibility;
  handoffBoundary: "lifecycle_handoff_only";
  updatedAt?: string | null;
  storageMode?: string;
};

export type LifecycleCustomerProjectEnvelope = {
  success: true;
  data: LifecycleCustomerProject;
};

export type LifecycleCustomerProjectListEnvelope = {
  success: true;
  data: {
  items: Array<LifecycleCustomerProject>;
  pagination: Pagination;
  storageMode?: string;
};
};

export type LifecycleCustomerQuotation = {
  quoteId?: string | null;
  status: string;
};

export type LifecycleCustomerReferences = {
  designId?: string | null;
  quoteId?: string | null;
  designPackageId?: string | null;
  customerReportUrl?: string | null;
};

export type LifecycleCustomerSolution = {
  systems: Array<string>;
  equipmentBrands: Array<"Rheem" | "Ruud" | "Everhot" | "unassigned">;
};

export type LifecycleCustomerVisibility = {
  scope: "customer-visible";
  hiddenFields: Array<"dealerMargin" | "costBaseline" | "internalApprovalNotes" | "crossTenantData" | "sensitiveTechnicianNotes">;
};

export type LifecycleDevice = LifecycleDeviceInput;

export type LifecycleDeviceInput = {
  sourceDeviceId?: string;
  id?: string;
  brand?: "Rheem" | "Ruud" | "Everhot" | "unassigned";
  productId?: string;
  productCode?: string;
  name?: string;
  model?: string;
  system?: string;
  serialNumber?: string;
  installLocation?: string;
  iotDeviceId?: string | null;
  capabilities?: Array<string>;
  status?: InstalledAssetStatus;
};

export type LifecycleHandover = {
  id?: string;
  _id?: string;
  tenantId: string;
  dealerId?: string | null;
  storeId?: string | null;
  customerId: string;
  opportunityId?: string;
  contractId: string;
  designId?: string;
  quoteId?: string;
  projectAddress?: string;
  projectState: LifecycleProjectState;
  customerVisibleState?: string;
  progressPercent?: number;
  currentMilestone?: string;
  designPackageId?: string;
  systems?: Array<string>;
  lifecycleStage: LifecycleStage;
  handoverStatus: HandoverStatus;
  iot: IotHandoff;
  devices?: Array<LifecycleDevice>;
  installedAssets: Array<InstalledAsset>;
  servicePlan: ServicePlan;
  createdBy?: string;
  updatedBy?: string;
  acceptedAt?: string;
  lastSyncedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  storageMode?: string;
};

export type LifecycleHandoverEnvelope = {
  success: true;
  data: LifecycleHandover;
};

export type LifecycleHandoverInput = {
  customerId: string;
  contractId: string;
  opportunityId?: string;
  designId?: string;
  quoteId?: string;
  designPackageId?: string;
  projectAddress?: string;
  projectState?: LifecycleProjectState;
  state?: LifecycleProjectState;
  systems?: Array<string>;
  devices?: Array<LifecycleDeviceInput>;
  installedAssets?: Array<InstalledAssetInput>;
  iot?: IotHandoffInput;
  servicePlan?: ServicePlanInput;
};

export type LifecycleHandoverListEnvelope = {
  success: true;
  data: {
  items: Array<LifecycleHandover>;
  pagination: Pagination;
  storageMode?: string;
};
};

export type LifecycleIotForbiddenControl = {
  realtimeControlCommands: false;
  remoteSetpointWrite: false;
  deviceActuation: false;
  reason: string;
};

export type LifecycleIotHandoffHome = {
  platform: string;
  homeId: string | null;
  accountId?: string | null;
  projectAddress?: string | null;
  systems?: Array<string>;
  projectState: LifecycleProjectState;
  customerVisibleState?: string | null;
  lifecycleStage: LifecycleStage;
  handoverStatus: HandoverStatus;
  acceptedAt?: string | null;
};

export type LifecycleIotHandoffPackage = {
  packageType: "rhautt-nexus-iot-lifecycle-handoff";
  packageVersion: "1.0";
  generatedAt: string;
  tenantId: string;
  dealerId?: string | null;
  storeId?: string | null;
  customerId: string;
  contractId: string;
  opportunityId?: string | null;
  quoteId?: string | null;
  designPackageId?: string | null;
  home: LifecycleIotHandoffHome;
  installedAssets: Array<InstalledAsset>;
  capabilityRegistry: Array<CapabilityRegistryItem>;
  servicePlan: ServicePlan;
  warrantySummary: LifecycleIotWarrantySummary;
  maintenanceSchedule: LifecycleIotMaintenanceSchedule;
  handoffBoundary: "lifecycle_handoff_only";
  forbiddenControl: LifecycleIotForbiddenControl;
  visibility: LifecycleIotHandoffPackageVisibility;
  storageMode?: string;
};

export type LifecycleIotHandoffPackageEnvelope = {
  success: true;
  data: LifecycleIotHandoffPackage;
};

export type LifecycleIotHandoffPackageVisibility = {
  scope: "iot-lifecycle-handoff";
  allowedFields: Array<string>;
  hiddenFields: Array<"dealerMargin" | "costBaseline" | "internalApprovalNotes" | "crossTenantData" | "sensitiveTechnicianNotes" | "realtimeControlCommands" | "remoteControlTokens">;
  sensitiveFieldPolicy: string;
};

export type LifecycleIotMaintenanceSchedule = {
  planId?: string | null;
  status: string;
  cadence: string;
  sla: string;
  dealerServiceOwner?: string | null;
  startDate?: string | null;
  nextMaintenanceAt?: string | null;
  assetCount: number;
  taskFamilies: Array<SystemCategory>;
};

export type LifecycleIotWarrantyAsset = {
  assetId: string;
  category?: SystemCategory;
  brand?: string;
  warranty?: Warranty;
  servicePlanCode?: string | null;
};

export type LifecycleIotWarrantySummary = {
  assetCount: number;
  warrantyMonths?: number | null;
  registrationStatus: {
  pending: number;
  registered: number;
  expired: number;
  unknown: number;
};
  assets: Array<LifecycleIotWarrantyAsset>;
};

export type LifecycleProjectState = "lead-created" | "diagnosis-in-progress" | "solution-drafted" | "design-in-progress" | "quote-drafted" | "quote-approved" | "contract-pending" | "construction-planning" | "construction-in-progress" | "acceptance-pending" | "accepted" | "lifecycle-handoff-ready" | "lifecycle-active" | "service-event-open";

export type LifecycleProjectStatePatch = {
  state: LifecycleProjectState;
  projectState?: LifecycleProjectState;
  customerVisibleState?: string;
  progressPercent?: number;
  currentMilestone?: string;
  lifecycleStage?: LifecycleStage;
  handoverStatus?: HandoverStatus;
  updatedBy?: string;
};

export type LifecycleProjectStatesEnvelope = {
  success: true;
  data: Record<string, {
  customerVisibleState: string;
  progressPercent: number;
  currentMilestone: string;
  lifecycleStage: LifecycleStage;
  handoverStatus: HandoverStatus;
}>;
};

export type LifecycleStage = "contracted" | "installing" | "accepted" | "iot_handover" | "operating" | "service";

export type ObservabilityMetrics = {
  window: {
  sampleSize: number;
  maxStored: number;
};
  requests: {
  total: number;
  status2xx: number;
  status4xx: number;
  status5xx: number;
  errorRate: number;
};
  latencyMs: {
  p50: number;
  p95: number;
  p99: number;
  max: number;
};
  recent: Array<Record<string, unknown>>;
};

export type ObservabilitySignals = {
  logs: "structured-http-events";
  traces: "request-id-and-trace-id";
  metrics: "in-process-http-window";
  exporter: "local-baseline" | "otel-otlp-configured";
};

export type ObservabilitySlo = {
  status: "within_slo" | "slo_risk";
  availability: number;
  targets: {
  availabilityTarget: number;
  p95LatencyMsTarget: number;
  p99LatencyMsTarget: number;
  sampleWindowRequests: number;
};
  checks: {
  availabilityOk: boolean;
  latencyP95Ok: boolean;
  latencyP99Ok: boolean;
};
  errorBudget: {
  targetAvailability: number;
  consumedBy5xxRate: number;
  remaining: number;
};
};

export type Pagination = {
  page: number;
  limit: number;
  total: number;
  pages: number;
};

export type ReactCandidateStatus = {
  enabled: boolean;
  status: "frozen" | "enabled-for-contract-validation";
  routes: Array<{
  name: string;
  path: string;
  mounted: boolean;
}>;
};

export type ReactCandidateStatusEnvelope = {
  success: true;
  data: ReactCandidateStatus;
};

export type ServicePlan = ServicePlanInput;

export type ServicePlanInput = {
  planId?: string;
  code?: string;
  status?: "draft" | "prepared" | "active" | "paused" | "expired";
  warrantyMonths?: number;
  maintenanceCadence?: string;
  sla?: string;
  dealerServiceOwner?: string;
  startDate?: string;
  nextMaintenanceAt?: string;
};

export type Store = {
  id: string;
  tenantId: string;
  dealerId: string;
  code: string;
  name: string;
  city?: string | null;
  address?: string | null;
  managerUserId?: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
};

export type SuccessEnvelope = {
  success: true;
  data?: Record<string, unknown>;
};

export type SystemCategory = "central-hot-water" | "heating" | "whole-air" | "fresh-air" | "air-conditioning" | "water-treatment" | "smart-control" | "unknown";

export type SystemPack = {
  id: string;
  name: string;
  category: "hot_water" | "heating" | "whole_air" | "smart_control";
  plugAndPlayRole: "anchor" | "cross_cutting";
  positioning: string;
  recommendedFor?: Array<string>;
  painPoints?: Array<string>;
  requiredInputs?: Array<string>;
  standards: Array<SystemPackStandard>;
  standardsCoverage: Array<SystemPackStandardsCoverage>;
  modules: Array<string>;
  deliverables: Array<string>;
  iotCapabilities: Array<string>;
  attachableTo?: Array<string>;
  quoteTags: Array<string>;
};

export type SystemPackComposition = {
  packs: Array<SystemPack>;
  modules: Array<string>;
  standards: Array<SystemPackStandard>;
  standardsCoverage: Array<SystemPackStandardsCoverage>;
  standardsEvidence: SystemPackStandardsEvidence;
  deliverables: Array<string>;
  iot: SystemPackIotHandoff;
  quoteTags: Array<string>;
  implementationNotes: Array<string>;
};

export type SystemPackCompositionEnvelope = {
  success: true;
  data: SystemPackComposition;
};

export type SystemPackEnvelope = {
  success: true;
  data: SystemPack;
};

export type SystemPackIotHandoff = {
  handoverRequired: boolean;
  lifecycleBridge: string;
  capabilities: Array<string>;
};

export type SystemPackListEnvelope = {
  success: true;
  data: Array<SystemPack>;
};

export type SystemPackRecommendation = {
  packs: Array<SystemPack>;
  reasons: Array<SystemPackRecommendationReason>;
};

export type SystemPackRecommendationEnvelope = {
  success: true;
  data: SystemPackRecommendation;
};

export type SystemPackRecommendationReason = {
  packId: string;
  name: string;
  reason: string;
};

export type SystemPackStandard = {
  level: "L1" | "L2" | "L3";
  code: string;
  edition: string;
  name: string;
  scope: string;
  softwareCheck: "mandatoryBlocker" | "calculationRule" | "acceptanceChecklist" | "advisoryOptimization";
};

export type SystemPackStandardsCoverage = {
  domain: SystemPackStandardsCoverageDomain;
  requiredFor: Array<string>;
  primaryStandards: Array<string>;
  softwareChecks: Array<string>;
  deliverableEvidence: Array<string>;
  quoteImpact: Array<string>;
  lifecycleHandoffImpact: Array<string>;
  packIds?: Array<string>;
};

export type SystemPackStandardsCoverageDomain = "thermal-comfort" | "ventilation-iaq" | "hot-water-safety" | "potable-water" | "energy" | "smart-interoperability";

export type SystemPackStandardsCoverageSummary = {
  status: "complete" | "incomplete";
  requiredDomains: Array<SystemPackStandardsCoverageDomain>;
  coveredDomains: Array<SystemPackStandardsCoverageDomain>;
  missingRequiredDomains: Array<SystemPackStandardsCoverageDomain>;
  domains: Array<SystemPackStandardsCoverage>;
};

export type SystemPackStandardsEvidence = {
  hierarchy: Array<SystemPackStandardsHierarchyLevel>;
  mandatoryBlockers: Array<string>;
  calculationRules: Array<string>;
  advisoryOptimizations: Array<string>;
  coverage: SystemPackStandardsCoverageSummary;
};

export type SystemPackStandardsHierarchyLevel = {
  level: "L1" | "L2" | "L3";
  label: string;
  enforcement: string;
  standards: Array<SystemPackStandard>;
};

export type Tenant = {
  id: string;
  code: string;
  name: string;
  type: "hq" | "regional" | "dealer_group";
  status: "active" | "inactive" | "suspended";
  settings: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
};

export type UpdateDealerInput = {
  code?: string;
  name?: string;
  province?: string | null;
  city?: string | null;
  contact?: Record<string, string>;
  contractLevel?: string;
  status?: string;
};

export type UpdateStoreInput = {
  dealerId?: string;
  code?: string;
  name?: string;
  city?: string | null;
  address?: string | null;
  managerUserId?: string | null;
  status?: string;
};

export type UpdateTenantInput = {
  code?: string;
  name?: string;
  type?: "hq" | "regional" | "dealer_group";
  status?: "active" | "inactive" | "suspended";
  settings?: Record<string, unknown>;
};

export type Warranty = {
  startDate?: string | null;
  endDate?: string | null;
  warrantyMonths?: number;
  registrationStatus?: "pending" | "registered" | "expired" | "unknown";
};

export type ApiEnvelope<T = unknown> = { success: true; data: T } | { success: false; error: string };

export type ClientParams = {
  path?: Record<string, string | number>;
  query?: Record<string, string | number | boolean | undefined | null>;
  body?: unknown;
  headers?: Record<string, string>;
};

export type RhauttNexusClientOptions = {
  baseUrl?: string;
  token?: string;
  fetchImpl?: typeof fetch;
};

export class RhauttNexusClient {
  private baseUrl: string;
  private token?: string;
  private fetchImpl: typeof fetch;

  constructor(options: RhauttNexusClientOptions = {}) {
    this.baseUrl = options.baseUrl || '';
    this.token = options.token;
    this.fetchImpl = options.fetchImpl || fetch;
  }

  setToken(token?: string) {
    this.token = token;
  }

  private buildUrl(routePath: string, params: ClientParams) {
    let url = routePath;
    for (const [key, value] of Object.entries(params.path || {})) {
      url = url.replace(`{${key}}`, encodeURIComponent(String(value)));
    }
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(params.query || {})) {
      if (value === undefined || value === null) continue;
      query.set(key, String(value));
    }
    const suffix = query.toString();
    return `${this.baseUrl}${url}${suffix ? `?${suffix}` : ``}`;
  }

  private async request<T>(method: string, routePath: string, params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(params.headers || {})
    };
    if (this.token) headers.Authorization = `Bearer ${this.token}`;
    const response = await this.fetchImpl(this.buildUrl(routePath, params), {
      method,
      headers,
      body: params.body === undefined || method === 'GET' ? undefined : JSON.stringify(params.body)
    });
    const payload = await response.json().catch(() => ({ success: false, error: response.statusText }));
    return payload as ApiEnvelope<T>;
  }

  private async requestBlob(method: string, routePath: string, params: ClientParams = {}): Promise<Response> {
    const headers: Record<string, string> = {
      ...(params.headers || {})
    };
    if (this.token) headers.Authorization = `Bearer ${this.token}`;
    return this.fetchImpl(this.buildUrl(routePath, params), {
      method,
      headers,
      body: params.body === undefined || method === 'GET' ? undefined : JSON.stringify(params.body)
    });
  }

  async activateContract<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/{id}/activate", params);
  }

  async addConstructionEvidence<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/construction/projects/{id}/evidence", params);
  }

  async addCrmInteraction<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/crm/interactions", params);
  }

  async adminCreateUser<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/admin/users", params);
  }

  async adminListUsers<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/auth/admin/users", params);
  }

  async adminResetUserPassword<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/admin/users/{id}/reset-password", params);
  }

  async adminUpdateUser<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PATCH", "/api/v2/auth/admin/users/{id}", params);
  }

  async archiveProductDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("DELETE", "/api/v2/product-catalog/devices/{id}", params);
  }

  async archiveSiteProductAssignment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("DELETE", "/api/v2/brand-sites/{siteCode}/product-assignments/{assignmentId}", params);
  }

  async cancelContract<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/{id}/cancel", params);
  }

  async candidateCopyProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects/{projectId}/copy", params);
  }

  async candidateCreateDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices", params);
  }

  async candidateCreateProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects", params);
  }

  async candidateDeleteDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("DELETE", "/api/v2/devices/{deviceId}", params);
  }

  async candidateDeleteProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("DELETE", "/api/v2/projects/{projectId}", params);
  }

  async candidateDeviceBatchOperation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices/batch", params);
  }

  async candidateDeviceCategoryStats<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/devices/stats/categories", params);
  }

  async candidateDeviceCompatibility<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices/compatibility", params);
  }

  async candidateExportDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/devices/export", params);
  }

  async candidateExportProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects/{projectId}/export", params);
  }

  async candidateFavoriteDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices/{deviceId}/favorite", params);
  }

  async candidateGetDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/devices/{deviceId}", params);
  }

  async candidateGetProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/projects/{projectId}", params);
  }

  async candidateGetSharedProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/projects/shared/{shareToken}", params);
  }

  async candidateImportDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices/import", params);
  }

  async candidateListDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/devices", params);
  }

  async candidateListProjects<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/projects", params);
  }

  async candidateListProjectVersions<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/projects/{projectId}/versions", params);
  }

  async candidateProjectBatchOperation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects/batch", params);
  }

  async candidateProjectStats<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/projects/stats", params);
  }

  async candidateRecommendDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/devices/recommend", params);
  }

  async candidateRestoreProjectVersion<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects/{projectId}/versions/{versionId}/restore", params);
  }

  async candidateReviewDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/devices/{deviceId}/review", params);
  }

  async candidateSearchDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/devices/search", params);
  }

  async candidateShareProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/projects/{projectId}/share", params);
  }

  async candidateUpdateDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/devices/{deviceId}", params);
  }

  async candidateUpdateProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/projects/{projectId}", params);
  }

  async changePassword<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/auth/password", params);
  }

  async completeConstructionMilestone<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/construction/projects/{id}/milestones/{key}/complete", params);
  }

  async completeDiagnosis<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/complete", params);
  }

  async completePublicDiagnosis<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/public/complete", params);
  }

  async composeSystemPacks<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/system-packs/compose", params);
  }

  async confirmDiagnosisDeposit<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/deposit/{depositId}/confirm", params);
  }

  async contractSignatureWebhook<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/webhook/qiyuesuo", params);
  }

  async createConstructionProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/construction/projects/from-contract", params);
  }

  async createContractDraft<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract", params);
  }

  async createContractFromQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contracts/from-quotation", params);
  }

  async createCrmLead<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/crm/leads", params);
  }

  async createDealer<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/dealers", params);
  }

  async createDiagnosisDepositIntent<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/deposit/intent", params);
  }

  async createLifecycleHandover<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/lifecycle/handover", params);
  }

  async createSiteProductAssignment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/brand-sites/{siteCode}/product-assignments", params);
  }

  async createStore<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/stores", params);
  }

  async createTenant<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/tenants", params);
  }

  async decideContractApproval<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contracts/{contractId}/approval", params);
  }

  async deleteProductRelation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("DELETE", "/api/v2/product-catalog/relations/{relId}", params);
  }

  async detectDiagnosisPainpoints<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/painpoints/detect", params);
  }

  async diagnosisCases<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/cases", params);
  }

  async diagnosisConsult<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/consult", params);
  }

  async diagnosisIndicativeQuote<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/quote", params);
  }

  async diagnosisPrincipleDiagram<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/principle-diagram", params);
  }

  async draftContractFromQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/from-quotation", params);
  }

  async exportQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/export", params);
  }

  async fulfillContract<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/{id}/fulfill", params);
  }

  async generateDelivery<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/generate", params);
  }

  async generateQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/generate", params);
  }

  async getAnalyticsOverview<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/analytics/overview", params);
  }

  async getBrandProduct<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/brand/{slug}/products/{sku}", params);
  }

  async getConstructionProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/delivery/construction/projects/{id}", params);
  }

  async getContract<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/contracts/{contractId}", params);
  }

  async getContractDraft<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/contract/{id}", params);
  }

  async getContractSignUrl<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/contract/{id}/sign-url", params);
  }

  async getCurrentUser<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/auth/me", params);
  }

  async getCustomer360<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/crm/customers/{customerId}", params);
  }

  async getDatabaseReadiness<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/health/db", params);
  }

  async getDealer<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/dealers/{id}", params);
  }

  async getDeliveryDocs<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/delivery/{orderNo}/docs", params);
  }

  async getDiagnosisDepositConfig<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/deposit/config", params);
  }

  async getDiagnosisPainpoints<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/painpoints", params);
  }

  async getDiagnosisReport<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/reports/{reportId}", params);
  }

  async getDiagnosisShareView<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/reports/{reportId}/share-view", params);
  }

  async getEntitlementMe<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/entitlement/me", params);
  }

  async getHealthHeartbeat<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/health/heartbeat", params);
  }

  async getHealthLive<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/health/live", params);
  }

  async getHealthObservability<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/health/observability", params);
  }

  async getHealthReady<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/health/ready", params);
  }

  async getLifecycleCustomerProject<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/customer-projects/{contractId}", params);
  }

  async getLifecycleHandover<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/handover/{contractId}", params);
  }

  async getLifecycleIotHandoffPackage<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/handover/{contractId}/handoff-package", params);
  }

  async getProductContentCoverage<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/content/coverage", params);
  }

  async getProductDedupeCandidates<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/dedupe-candidates", params);
  }

  async getProductDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/devices/{id}", params);
  }

  async getProductTaxonomy<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/taxonomy", params);
  }

  async getPublicDiagnosisReport<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/public/reports/{reportId}", params);
  }

  async getPublicSiteProduct<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/sites/{siteCode}/products/{publicSlug}", params);
  }

  async getReactCandidateStatus<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/react-candidate/status", params);
  }

  async getStore<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/stores/{id}", params);
  }

  async getSystemPack<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/system-packs/{packId}", params);
  }

  async getTenant<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/tenants/{id}", params);
  }

  async getUser<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/auth/user", params);
  }

  async grantEntitlement<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/entitlement/grant", params);
  }

  async hideSiteProductAssignment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/brand-sites/{siteCode}/product-assignments/{assignmentId}/hide", params);
  }

  async listAuditEvents<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/audit/events", params);
  }

  async listBrandProducts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/brand/{slug}/products", params);
  }

  async listConstructionProjects<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/delivery/construction/projects", params);
  }

  async listContractDrafts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/contract", params);
  }

  async listContracts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/contracts", params);
  }

  async listCrmPipeline<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/crm/pipeline", params);
  }

  async listCustomers<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/crm/customers", params);
  }

  async listDealers<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/dealers", params);
  }

  async listDiagnosisReports<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/diagnosis/reports", params);
  }

  async listEntitlementSubscriptions<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/entitlement/subscriptions", params);
  }

  async listLifecycleCustomerProjects<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/customer-projects", params);
  }

  async listLifecycleHandovers<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/handover", params);
  }

  async listProductContent<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/devices/{id}/content", params);
  }

  async listProductDevices<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/devices", params);
  }

  async listProductRelations<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/product-catalog/devices/{id}/relations", params);
  }

  async listProjectStates<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/lifecycle/project-states", params);
  }

  async listPublicSiteProducts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/sites/{siteCode}/products", params);
  }

  async listQuotations<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/quotation", params);
  }

  async listSiteProductAssignments<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/brand-sites/{siteCode}/product-assignments", params);
  }

  async listStores<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/stores", params);
  }

  async listSystemPacks<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/system-packs", params);
  }

  async listTenants<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("GET", "/api/v2/tenants", params);
  }

  async lockQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/{id}/lock", params);
  }

  async login<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/login", params);
  }

  async loginWithSms<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/login-sms", params);
  }

  async logout<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/logout", params);
  }

  async markContractSigned<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contracts/{contractId}/signature", params);
  }

  async markLifecycleAccepted<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/lifecycle/handover/{contractId}/acceptance", params);
  }

  async payConstructionPayment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/construction/projects/{id}/payments/{kind}/pay", params);
  }

  async persistQuotation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation", params);
  }

  async publicDiagnosisAiAnalyze<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/public/ai-analyze", params);
  }

  async publicDiagnosisRecommend<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/public/recommend", params);
  }

  async publicIngressCaptureLead<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/ingress/lead", params);
  }

  async publishDueProductContent<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/content/publish-due", params);
  }

  async publishSiteProductAssignment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/brand-sites/{siteCode}/product-assignments/{assignmentId}/publish", params);
  }

  async quotationEconetPremium<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/econet-premium", params);
  }

  async quotationGuardrailCheck<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/guardrail-check", params);
  }

  async quotationLoadCalc<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/quotation/load-calc", params);
  }

  async recommendBrandProducts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/brand/{slug}/recommend", params);
  }

  async recommendProducts<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/recommend", params);
  }

  async recommendSystemPacks<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/system-packs/recommend", params);
  }

  async recordContractPayment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contracts/{contractId}/payments", params);
  }

  async refreshToken<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/refresh-token", params);
  }

  async refundDiagnosisDeposit<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/deposit/{depositId}/refund", params);
  }

  async register<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/register", params);
  }

  async revokeDiagnosisReport<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/reports/{reportId}/revoke", params);
  }

  async revokeEntitlement<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/entitlement/revoke", params);
  }

  async sendContractForSignature<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/{id}/send", params);
  }

  async sendSms<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/auth/send-sms", params);
  }

  async setDiagnosisDepositConfig<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/diagnosis/deposit/config", params);
  }

  async signContractOffline<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contract/{id}/sign", params);
  }

  async signCrmOpportunity<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/crm/opportunities/{id}/sign", params);
  }

  async startConstructionMilestone<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/delivery/construction/projects/{id}/milestones/{key}/start", params);
  }

  async startContractDelivery<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/contracts/{contractId}/delivery-start", params);
  }

  async transitionProductContent<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/devices/{id}/content/{locale}/transition", params);
  }

  async updateCrmOpportunity<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/crm/opportunities/{id}", params);
  }

  async updateCrmOpportunityStage<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/crm/opportunities/{id}/stage", params);
  }

  async updateDealer<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/dealers/{id}", params);
  }

  async updateLifecycleState<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PATCH", "/api/v2/lifecycle/handover/{contractId}/state", params);
  }

  async updateProductDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PATCH", "/api/v2/product-catalog/devices/{id}", params);
  }

  async updateSiteProductAssignment<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PATCH", "/api/v2/brand-sites/{siteCode}/product-assignments/{assignmentId}", params);
  }

  async updateStore<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/stores/{id}", params);
  }

  async updateTenant<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/tenants/{id}", params);
  }

  async updateUser<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("PUT", "/api/v2/auth/user", params);
  }

  async upsertProductContent<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/devices/{id}/content", params);
  }

  async upsertProductDevice<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/devices", params);
  }

  async upsertProductRelation<T = unknown>(params: ClientParams = {}): Promise<ApiEnvelope<T>> {
    return this.request<T>("POST", "/api/v2/product-catalog/devices/{id}/relations", params);
  }
}

export function createRhauttNexusClient(options: RhauttNexusClientOptions = {}) {
  return new RhauttNexusClient(options);
}
